/* global systemDictionary:true */
'use strict';

systemDictionary = {
    "Auto": {
        "en": "Auto",
        "de": "Auto",
        "ru": "Автоматически",
        "pt": "Auto",
        "nl": "Auto",
        "fr": "Auto",
        "it": "Auto",
        "es": "Auto",
        "pl": "Auto"
    },
    "Manual": {
        "en": "Manual",
        "de": "Manual",
        "ru": "Вручную",
        "pt": "Manual",
        "nl": "Met de hand",
        "fr": "Manuel",
        "it": "Manuale",
        "es": "Manual",
        "pl": "Manual"
    },
    "on save adapter restarts with new config immediately": {
        "en": "on save adapter restarts with new config immediately",
        "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
        "ru": "При сохранении настроек адаптера он сразу же перезапускается",
        "pt": "no adaptador de salvar reinicia com nova configuração imediatamente",
        "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config",
        "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement",
        "it": "su save adapter si riavvia immediatamente con la nuova configurazione",
        "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato",
        "pl": "on save adapter restarts with new config immediately"
    },
    "ringdescription": {
        "en": "This adapter needs a valid token. To generate it, follow the description in the readme.",
        "de": "Dieser Adapter benötigt einen gültigen Token. Um es zu erzeugen, folgen Sie der Beschreibung im Readme.",
        "ru": "Этот адаптер нужен действительный токен. Чтобы сгенерировать его, следуйте описанию в читаю.",
        "pt": "Este adaptador precisa de um token válido. Para gerenciá-lo, siga a descrição no readme.",
        "nl": "Deze adapter heeft een geldig teken nodig. Om het te genereren, de beschrijving in de lezing te volgen.",
        "fr": "Cet adaptateur a besoin d'un jeton valide. Pour le générer, suivez la description dans le readme.",
        "it": "Questo adattatore ha bisogno di un token valido. Per generarlo, seguire la descrizione nel testo.",
        "es": "Este adaptador necesita un token válido. Para generarlo, siga la descripción en el readme.",
        "pl": "Ta adapter potrzebuje odpowiedniego symbolu. W celu generowania go, podąża za opisem w gotowości.",
        "uk": "Цей адаптер потребує дійсного токену. Щоб створити його, слідуйте опису в чителю.",
        "zh-cn": "这种适应者需要一个有效的基础。 为产生这一趋势,在读者说明之后。."
    },
    "info": {
        "en": "<br>Important information!<br>The settings \"Overlaying text\", \"Picture sharpening\" and \"Picture contrast\" are time consuming (up to a few Seconds).<br>If a fast display time is important, please turn them all off.<br><br>Tip: Picture sharpening and Picture contrast working best at night.",
        "de": "<br>Wichtige Informationen!<br>Die Einstellungen \"Überlagerungstext\", \"Bildschärfe\" und \"Bildkontrast\" sind zeitaufwendig (bis zu einigen Sekunden).<br>Wenn eine schnelle Anzeigezeit wichtig ist, bitte abschalten.<br><br>Tipp: Bildschärfe und Bildkontrast arbeiten am Besten in der Nacht.",
        "ru": "<br>Важная информация!<br>Настройки \"Overlaying текст\", \"Заточка изображения\" и \"Рисунок контраст\" теряют время (до нескольких секунд).<br>Если быстрое время отображения важно, пожалуйста, выключите их все.<br><br>Совет: заточка изображения и контраст изображения работают лучше всего ночью.",
        "pt": "<br>InformaÃ§Ã£o Importante!<br>As definições \"Sobreposição de texto\", \"Afiar imagem\" e \"Contraste de imagem\" são demorados (até alguns segundos).<br>Se um tempo de exibição rápido é importante, por favor, desligue todos.<br><br>Dica: Afiação de imagem e contraste de imagem que funcionam melhor à noite.",
        "nl": "<br>Belangrijke informatie!<br>De setting \"Vertaling:, \"Picture scherp\" en \"In tegenstelling tot\" het is tijd voor een paar seconden.<br>Als een snelle tijd belangrijk is, zet ze dan allemaal uit.<br><br>Foto's slijpend en Picture contrast werkt 's nachts het beste.",
        "fr": "<br>Informations importantes !<br>Les paramètres \"Remplacer le texte\", \"Aiguillage de la photo\" et \"Contraste visuel\" consomme du temps (jusqu'à quelques secondes).<br>Si un temps d'affichage rapide est important, veuillez les éteindre.<br><br>Astuce: Aiguillage d'image et contraste d'image fonctionne le mieux la nuit.",
        "it": "<br>Informazioni importanti!<br>Le impostazioni \"Testo di sovrapposizione\", \"Immagine affilare\" e \"Contrasto immagine\" consumano tempo (fino a pochi secondi).<br>Se un tempo di visualizzazione veloce è importante, si prega di spegnerli tutti.<br><br>Suggerimento: Immagine affilare e Immagine contrasto funziona meglio di notte.",
        "es": "<br>¡Información importante!<br>La configuración \"Texto superpuesto\", \"Afilado de la imagen\" y \"Contraste de imagen\" son el consumo de tiempo (hasta unos segundos).<br>Si un tiempo de visualización rápido es importante, por favor apague todos.<br><br>Consejo: Afilado de imágenes y contraste de imagen trabajando mejor por la noche.",
        "pl": "<br>Important information!<br>Ustawienia  \"Tekst Overlaying\", \"Zdjęcie ostrym\" i \"Kontrast\" czas spędzania czasu (do kilku sekund).<br>Jeśli czas szybkiego wyświetlania jest bardzo ważny, to wszystko się odwraca.<br>Tip: ostry film i film kontrastują w nocy.<br><br>Tip: ostry film i film kontrastują w nocy.",
        "uk": "<br>Головна!<br>Налаштування \"Налаштування тексту\", \"Заточування зображень\" і \"Фото контраст\" час споживання (до декількох секунд).<br>Якщо час швидкого відображення важливо, будь ласка, ввімкніть їх всі.<br><br>Порада: малюнок заточування і контрастність зображень найкраще працює вночі.",
        "zh-cn": "<br>重要信息!<br>环境 \"全文\", \"B. 加剧和加剧\" A. \"形状\" 现在耗费时间(几秒)。.<br>如果快速展示时间很重要,请将其赶出。.<br><br>参与:在夜间最好地进行紧张和紧张关系。."
    },
    "User": {
        "en": "User",
        "de": "Benutzer",
        "ru": "пользователь",
        "pt": "Do utilizador",
        "nl": "Gebruiker",
        "fr": "Utilisateur",
        "it": "Utente",
        "es": "Usuario",
        "pl": "Użytkownik"
    },
    "Confirm Password": {
        "en": "Confim Password",
        "de": "Bestätige das Passwort",
        "ru": "Подтвердите Пароль",
        "pt": "Confirme a Senha",
        "nl": "bevestig wachtwoord",
        "fr": "Confirmez le mot de passe",
        "it": "conferma password",
        "es": "Confirmar contraseña",
        "pl": "Potwierdź hasło"
    },
    "Password Enable": {
        "en": "Login with password",
        "de": "Einloggen mit Passwort",
        "ru": "Вход с паролем",
        "pt": "Login com senha",
        "nl": "Inloggen met wachtwoord",
        "fr": "Se connecter avec mot de passe",
        "it": "Accedi con password",
        "es": "Iniciar sesión con contraseña",
        "pl": "Zaloguj się za pomocą hasła"
    },
    "ring-api": {
        "en": "RING-API (Default)",
        "de": "RING-API (Stanard Einstellung)",
        "ru": "RING-API (по умолчанию)",
        "pt": "RING-API (padrão)",
        "nl": "RING-API (standaard)",
        "fr": "RING-API (par défaut)",
        "it": "RING-API (predefinito)",
        "es": "RING-API (por defecto)",
        "pl": "RING-API (domyślnie)",
        "zh-cn": "RING-API（默认）"
    },
    "Filename": {
        "en": "Filename",
        "de": "Dateiname",
        "ru": "Имя файла",
        "pt": "Nome do arquivo",
        "nl": "Veldnaam",
        "fr": "Nom du fichier",
        "it": "Nome del file",
        "es": "Nombre de archivo",
        "pl": "Filename",
        "uk": "Назва файлу",
        "zh-cn": "导 言"
    },
    "Automatic recording time in seconds": {
        "en": "Automatic recording time in seconds",
        "de": "Automatische Aufnahmezeit in Sekunden",
        "ru": "Автоматическое время записи в секундах",
        "pt": "Tempo automático de gravação em segundos",
        "nl": "Automatische opnametijd in seconden",
        "fr": "Temps d'enregistrement automatique en secondes",
        "it": "Tempo di registrazione automatico in secondi",
        "es": "Tiempo de grabación automático en segundos",
        "pl": "Czas nagrywania automatycznego na sekundę",
        "uk": "Автоматичний час запису в секундах",
        "zh-cn": "第二期自动记录时间"
    },
    "Recording time in seconds": {
        "en": "Recording time on manual trigger in seconds",
        "de": "Aufnahmezeit auf manuellem Trigger in Sekunden",
        "ru": "Время записи на ручный триггер за считанные секунды",
        "pt": "Tempo de gravação no gatilho manual em segundos",
        "nl": "De tijd van de handleiding in seconden",
        "fr": "Temps d'enregistrement sur le déclencheur manuel en quelques secondes",
        "it": "Tempo di registrazione sul trigger manuale in pochi secondi",
        "es": "Tiempo de grabación en el gatillo manual en segundos",
        "pl": "Czas nagrywania ręcznego spustu w sekundach",
        "uk": "Час запису на ручний тригер за секундами",
        "zh-cn": "二. 第二期机的录音时间"
    },
    "Auto event": {
        "en": "React on Event automatically",
        "de": "Auf Ereignisse automatisch reagieren",
        "ru": "Реагировать на событие автоматически",
        "pt": "Reagir no Evento automaticamente",
        "nl": "Reageer automatisch",
        "fr": "Réagir sur Event automatiquement",
        "it": "Reagisci automaticamente su Event",
        "es": "Reaccionar en el evento automáticamente",
        "pl": "Reaktywacja zdarzeń automatycznie",
        "uk": "React на заході автоматично",
        "zh-cn": "对活动的反应"
    },
    "Path": {
        "en": "Path",
        "de": "Pfad",
        "ru": "Путь",
        "pt": "Caminho",
        "nl": "Path",
        "fr": "Sentier",
        "it": "Sentiero",
        "es": "Camino",
        "pl": "Path Path",
        "uk": "Патент",
        "zh-cn": "Path"
    },
    "Overlay": {
        "en": "Overlaying text",
        "de": "Überlagerungstext",
        "ru": "Overlaying текст",
        "pt": "Sobreposição de texto",
        "nl": "Vertaling:",
        "fr": "Remplacer le texte",
        "it": "Testo di sovrapposizione",
        "es": "Texto superpuesto",
        "pl": "Tekst Overlaying",
        "uk": "Налаштування тексту",
        "zh-cn": "全文"
    },
    "Sharpening": {
        "en": "Picture sharpening",
        "de": "Bildschärfe",
        "ru": "Заточка изображения",
        "pt": "Afiação de imagem",
        "nl": "Foto slijpen",
        "fr": "Aiguillage photo",
        "it": "Affilare l'immagine",
        "es": "Afilado de la imagen",
        "pl": "Zdjęcie ostrym",
        "uk": "Заточування зображень",
        "zh-cn": "急诊"
    },
    "wo": {
        "en": "without",
        "de": "ohne",
        "ru": "без",
        "pt": "sem",
        "nl": "zonder",
        "fr": "sans",
        "it": "senza",
        "es": "sin",
        "pl": "bezpłodnie",
        "uk": "без",
        "zh-cn": "无"
    },
    "less": {
        "en": "less",
        "de": "weniger",
        "ru": "меньше",
        "pt": "menos",
        "nl": "minder minder",
        "fr": "moins",
        "it": "meno",
        "es": "menos",
        "pl": "mniej",
        "uk": "менше",
        "zh-cn": "减少"
    },
    "more": {
        "en": "more",
        "de": "mehr",
        "ru": "больше",
        "pt": "mais",
        "nl": "meer meer",
        "fr": "plus",
        "it": "più",
        "es": "más",
        "pl": "bardziej",
        "uk": "більше",
        "zh-cn": "更多"
    },
    "much": {
        "en": "much",
        "de": "viel",
        "ru": "много",
        "pt": "muito",
        "nl": "veel",
        "fr": "beaucoup",
        "it": "molto",
        "es": "mucho",
        "pl": "dużo",
        "uk": "багато",
        "zh-cn": "很多"
    },
    "most": {
        "en": "most",
        "de": "am meisten",
        "ru": "наиболее",
        "pt": "o mais",
        "nl": "het meest",
        "fr": "le plus",
        "it": "il più",
        "es": "el más",
        "pl": "najbardziej",
        "uk": "найпопулярніші",
        "zh-cn": "最主要的是"
    },
    "Contrast": {
        "en": "Picture contrast",
        "de": "Bildkontrast",
        "ru": "Рисунок контраст",
        "pt": "Contraste de imagem",
        "nl": "In tegenstelling tot",
        "fr": "Contraste visuel",
        "it": "Contrasto immagine",
        "es": "Contraste de imagen",
        "pl": "Kontrast",
        "uk": "Фото контраст",
        "zh-cn": "A. 形状"
    },
    "only at Night": {
        "en": "Active only at night.",
        "de": "Nur nachts aktiv.",
        "ru": "Активно только ночью.",
        "pt": "Ativa apenas à noite.",
        "nl": "Alleen 's nachts actief.",
        "fr": "Active seulement la nuit.",
        "it": "Attivo solo di notte.",
        "es": "Activo sólo por la noche.",
        "pl": "Działa tylko w nocy.",
        "uk": "Активний тільки вночі.",
        "zh-cn": "只在夜间采取行动。."
    },
    "Set two face auth (once)": {
        "en": "Set two face auth (once)",
        "de": "Setze Tow Face Authentification (einmal)",
        "ru": "Установить два лица аутентификации (один раз)",
        "pt": "Definir autenticação de duas faces (uma vez)",
        "nl": "Stel twee gezichtsverificatie in (eenmalig)",
        "fr": "Définir l'authentification à deux faces (une fois)",
        "it": "Imposta un'autenticazione a due volti (una volta)",
        "es": "Establecer dos caras de autenticación (una vez)",
        "pl": "Ustaw dwa uwierzytelnianie twarzy (raz)",
        "zh-cn": "设置两张面孔身份验证（一次）"
    },
    "Refreshtoken (Two Face Auth)": {
        "en": "Refreshtoken (Two Face Auth)",
        "de": "Refreshtoken (Two Face Auth)",
        "ru": "Refreshtoken (аутентификация двух лиц)",
        "pt": "Atualizar atualização (autenticação de duas faces)",
        "nl": "Refreshtoken (Two Face Auth)",
        "fr": "Refreshtoken (authentification à deux faces)",
        "it": "Refreshtoken (Two Face Auth)",
        "es": "Refreshtoken (autenticación de dos caras)",
        "pl": "Refreshtoken (uwierzytelnianie dwóch twarzy)",
        "zh-cn": "刷新令牌（两面验证）"
    },
    "Delete old one": {
        "en": "Delete old files",
        "de": "Alte Dateien löschen",
        "ru": "Удалить старые файлы",
        "pt": "Excluir arquivos antigos",
        "nl": "Verwijder oude dossiers",
        "fr": "Supprimer les vieux fichiers",
        "it": "Eliminare vecchi file",
        "es": "Eliminar archivos antiguos",
        "pl": "Delete stare pliki",
        "uk": "Видалити старі файли",
        "zh-cn": "删除旧档案"
    },
    "Allow to transfer errors if the adapter crash. Private data like usernames, passwords, tokens, ... will be NOT be transferd.": {
        "en": "Allow to transfer errors if the adapter crash. Private data like usernames, passwords, tokens, ... will be NOT be transferd.",
        "de": "Erlaube das weiterleiten von Fehlern wenn der Adapter abstürtzt. Private Daten wie z.B. Benutzername, Passwort, Token, ... werden NICHT übertragen.",
        "ru": "Разрешить передавать ошибки в случае сбоя адаптера. Личные данные, такие как имена пользователей, пароли, токены, ... НЕ будут передаваться.",
        "pt": "Permitir a transferência de erros se o adaptador travar. Dados privados como nomes de usuário, senhas, tokens, ... NÃO serão transferidos.",
        "nl": "Sta toe om fouten over te dragen als de adapter crasht. Privégegevens zoals gebruikersnamen, wachtwoorden, tokens, ... worden NIET overgedragen.",
        "fr": "Permet de transférer des erreurs en cas de panne de l'adaptateur. Les données privées comme les noms d'utilisateur, les mots de passe, les jetons, ... ne seront PAS transférées.",
        "it": "Consentire il trasferimento degli errori in caso di arresto anomalo dell'adattatore. I dati privati come nomi utente, password, token, ... NON saranno trasferiti.",
        "es": "Permita transferir errores si el adaptador falla. NO se transferirán datos privados como nombres de usuario, contraseñas, tokens, ...",
        "pl": "Zezwól na przesyłanie błędów w przypadku awarii adaptera. Prywatne dane, takie jak nazwy użytkowników, hasła, tokeny, ... NIE zostaną przeniesione.",
        "zh-cn": "如果适配器崩溃，则允许传输错误。用户名，密码，令牌等私密数据将不会被传输。"
    }
};
